version: '3.4'


services:
  railwaywizzardapp:
    image: ${DOCKER_REGISTRY-}railwaywizzardapp
    build:
      context: .
      dockerfile: RailwayWizzard.App/Dockerfile
    ports:
      - "5178:80"
    depends_on:
      - postgres_db
      - php_service
    networks:
      - my-network
    restart: always

  postgres_db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwertyuiop
      POSTGRES_DB: railwaywizzardapp_dev
    ports:
      - "5433:5433"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    command: -p 5433
    networks:
      - my-network
    restart: always

  php_service:
    image: ${DOCKER_REGISTRY-}php_service
    build:
      context: .
      dockerfile: RailwayWizzard.RzdApi/Dockerfile
    ports:
      - "8088:8088"
    volumes:
      - ./RailwayWizzard.RzdApi/:/app
    working_dir: /app/examples
    networks:
      - my-network
    restart: always

  bot_service:
    image: ${DOCKER_REGISTRY-}bot_service
    build:
      context: .
      dockerfile: RailwayWizzard.Bot/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./RailwayWizzard.Bot:/app
    working_dir: /app
    depends_on:
      - railwaywizzardapp
    networks:
      - my-network
    restart: always

networks:
  my-network:
    driver: "bridge"

volumes:
  postgres-data: